# Generated by Django 4.2.9 on 2024-08-15 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_nombre_alter_article_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras, números y espacios.', regex='^[a-zA-Z0-9\\s]+$')]),
        ),
    ]
