# Generated by Django 4.2.9 on 2024-09-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos/'),
        ),
    ]
