# Generated by Django 4.2.9 on 2024-09-19 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='nombre',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras (incluyendo tildes), números y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s]+$')]),
        ),
    ]
