# Generated by Django 5.0.7 on 2024-09-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0005_alter_article_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
