# Generated by Django 4.2.9 on 2024-08-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalles_venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
