# Generated by Django 5.0.7 on 2024-08-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_article_nombre_alter_article_precio_and_more"),
        ("detalles_venta", "0003_detalleventa_venta"),
        (
            "ventas",
            "0004_rename_producto_venta_articulo_remove_venta_cantidad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="cantidad",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="ventas.venta",
            ),
        ),
    ]
