# Generated by Django 5.0.7 on 2024-08-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detalles_venta", "0004_alter_detalleventa_articulo_and_more"),
        (
            "ventas",
            "0004_rename_producto_venta_articulo_remove_venta_cantidad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ventas.venta",
            ),
        ),
    ]
