# Generated by Django 5.0.7 on 2024-08-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detalles_venta", "0005_alter_detalleventa_venta"),
        (
            "ventas",
            "0004_rename_producto_venta_articulo_remove_venta_cantidad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="venta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="ventas.venta",
            ),
        ),
    ]
