# Generated by Django 5.0.7 on 2024-09-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("detalles_venta", "0006_alter_detalleventa_venta"),
        ("ventas", "0005_remove_venta_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalleventa",
            name="articulo",
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="venta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="ventas.venta",
            ),
        ),
    ]
