# Generated by Django 5.0.7 on 2024-09-12 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_nombre"),
        ("detalles_venta", "0007_remove_detalleventa_articulo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleventa",
            name="articulo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
            ),
        ),
    ]
