# Generated by Django 5.0.7 on 2024-09-13 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_nombre"),
        ("detalles_venta", "0008_detalleventa_articulo"),
        ("ventas", "0006_remove_venta_articulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventa",
            name="articulo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="detalleventa",
            name="venta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="ventas.venta",
            ),
        ),
    ]
