# Generated by Django 4.2.9 on 2024-10-09 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_id'),
        ('detalles_venta', '0009_alter_detalleventa_articulo_alter_detalleventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
