# Generated by Django 4.2.9 on 2024-08-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_cantidad_venta_cliente_venta_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
