# Generated by Django 5.0.7 on 2024-09-11 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ventas",
            "0004_rename_producto_venta_articulo_remove_venta_cantidad_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="total",
        ),
    ]
