# Generated by Django 5.0.7 on 2024-09-12 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0005_remove_venta_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venta",
            name="articulo",
        ),
    ]
