# Generated by Django 5.0.7 on 2024-09-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clientes", "0001_initial"),
        ("ventas", "0006_remove_venta_articulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.clientes"
            ),
        ),
    ]
