# Generated by Django 5.0.7 on 2024-09-18 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0007_alter_venta_cliente"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venta",
            old_name="cliente",
            new_name="clientes",
        ),
    ]
