# Generated by Django 5.0.7 on 2024-10-15 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ventas", "0012_alter_venta_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
