from django.urls import path
from . import views

urlpatterns = [
    
    path('', views.ardecors, name='ardecors'),
    path('productos/', views.productos, name='productos'),
    path('sobre/', views.sobre, name='sobre'),
    path('contacto/', views.contacto, name='contacto'),
    path('iniciar_sesion/', views.iniciar_sesion, name='iniciar_sesion'),
    path('registro/', views.registro, name='registro'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('crear_usuario/', views.crear_usuario, name='crear_usuario'),
    path('lista_usuarios/', views.lista_usuarios, name='lista_usuarios'),
    path('eliminar_articles/', views.eliminar_articles, name='eliminar_articles'),
    path('crear_articles/', views.crear_articles, name='crear_articles'),
    path('lista_articles/', views.lista_articles, name='_articles'),
    path('base_articles/', views.base_articles, name='base_articles'),
    path('crear_venta/', views.crear_venta, name='crear_venta'),
    path('lista_ventas/', views.lista_ventas, name='lista_ventas'),
    path('crear_detalle_venta/', views.crear_detalle_venta, name='crear_detalle_venta'),
    path('lista_detalles_venta/', views.lista_detalles_venta, name='lista_detalles_venta'),
    path('crear_orden_compra/', views.crear_orden_compra, name='crear_orden_compra'),
    path('lista_ordenes_compra/', views.lista_ordenes_compra, name='lista_ordenes_compra'),
    path('crear_detalle_compra/', views.crear_detalle_compra, name='crear_detalle_compra'),
    path('lista_detalles_compra/', views.lista_detalles_compra, name='lista_detalles_compra'),
    path('eliminar_detalle_compra/', views.eliminar_detalles_compra, name='eliminar_detalles_compra'),
    path('crear_proveedor/', views.crear_proveedor, name='crear_proveedor'),
    path('lista_proveedores/', views.lista_proveedores, name='lista_proveedores'),
    path('crear_configuracion/', views.crear_configuracion, name='crear_configuracion'),
    path('lista_configuraciones/', views.lista_configuraciones, name='lista_configuraciones'),
    path('ardecors/', views.ardecors, name='ardecors'),
    path('iniciar_sesion/', views.iniciar_sesion, name='iniciar_sesion'),
    path('detalles_compra/crear/', views.crear_detalle_compra, name='crear_detalle_compra'),
    path('ver_carrito/', views.ver_carrito, name='ver_carrito'),
    path('pagar/', views.pagar, name='pagar'),
    path('agregar_al_carrito/<int:producto_id>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('logout/', views.logout_view, name='logout'),
]
