# Generated by Django 5.0.7 on 2024-09-19 20:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("proveedores", "0002_alter_proveedor_email_alter_proveedor_nombre_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insumos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El nombre solo puede contener letras (incluyendo tildes), números y espacios.",
                                regex="^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s]+$",
                            )
                        ],
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0.01, message="El precio debe ser un número positivo."
                            )
                        ],
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0,
                                message="El stock debe ser un número positivo o cero.",
                            )
                        ]
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proveedores.proveedor",
                    ),
                ),
            ],
        ),
    ]
