# Generated by Django 4.2.9 on 2024-10-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumos',
            options={'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
    ]
