# Generated by Django 4.2.9 on 2024-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admininstrador'), ('employee', 'Empleado')], default='employee', max_length=10),
        ),
    ]
