# Generated by Django 5.0.7 on 2024-10-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuarios", "0010_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("employee", "Empleado")],
                default="employee",
                max_length=10,
            ),
        ),
    ]
