# Generated by Django 4.2.9 on 2024-10-16 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El número de documento debe tener entre 8 y 10 dígitos.', regex='^\\d{8,10}$')]),
        ),
    ]
