# Generated by Django 4.2.9 on 2024-08-03 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdenCompra',
            new_name='Compras',
        ),
    ]
