# Generated by Django 4.2.9 on 2024-08-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_rename_ordencompra_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='producto',
            field=models.CharField(default='Producto no especificado', max_length=255),
        ),
        migrations.AlterField(
            model_name='compras',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
