# Generated by Django 5.0.7 on 2024-09-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0004_remove_compras_total_alter_compras_producto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compras",
            name="producto",
        ),
        migrations.AddField(
            model_name="compras",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
