# Generated by Django 4.2.9 on 2024-10-09 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_options'),
        ('compras', '0005_remove_compras_producto_compras_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compras',
            options={'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='proveedores.proveedor'),
        ),
    ]
