# Generated by Django 5.0.7 on 2024-10-15 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0009_alter_compras_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compras",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
