# Generated by Django 5.0.7 on 2024-09-11 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proveedor",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nombre",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El nombre solo puede contener letras y espacios.",
                        regex="^[a-zA-Z\\s]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=13,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número de teléfono debe tener el formato +57 seguido de 10 dígitos.",
                        regex="^\\+57[3][0-9]{9}$",
                    )
                ],
            ),
        ),
    ]
