# Generated by Django 5.0.7 on 2024-09-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0004_remove_compras_total_alter_compras_producto"),
        (
            "detalles_compra",
            "0002_remove_detallecompra_articulo_detallecompra_compra_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallecompra",
            name="producto",
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="cantidad",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="compra",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="compras.compras",
            ),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="total",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
