# Generated by Django 5.0.7 on 2024-09-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0005_remove_compras_producto_compras_total"),
        ("detalles_compra", "0003_remove_detallecompra_producto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detallecompra",
            name="fecha",
        ),
        migrations.AddField(
            model_name="detallecompra",
            name="producto",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="compra",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="compras.compras",
            ),
        ),
    ]
