# Generated by Django 4.2.9 on 2024-10-09 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        ('detalles_compra', '0005_remove_detallecompra_producto_detallecompra_insumo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compra'},
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_compra', to='insumos.insumos'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
