# Generated by Django 5.0.7 on 2024-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("tamaño", models.IntegerField(blank=True, null=True)),
                ("color", models.TextField(blank=True, null=True)),
                (
                    "titulo",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Título"
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        null=True, upload_to="imagenes", verbose_name="Imagen"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "precio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
