# Generated by Django 5.0.7 on 2024-08-02 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
